// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: pb/comment_service/service.proto

package comment_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllByStoryIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoryId int64 `protobuf:"varint,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
}

func (x *FindAllByStoryIDRequest) Reset() {
	*x = FindAllByStoryIDRequest{}
	mi := &file_pb_comment_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByStoryIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByStoryIDRequest) ProtoMessage() {}

func (x *FindAllByStoryIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_comment_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByStoryIDRequest.ProtoReflect.Descriptor instead.
func (*FindAllByStoryIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_comment_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllByStoryIDRequest) GetStoryId() int64 {
	if x != nil {
		return x.StoryId
	}
	return 0
}

var File_pb_comment_service_service_proto protoreflect.FileDescriptor

var file_pb_comment_service_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x20, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x32, 0x6f,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5d, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x44, 0x12, 0x2b, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42,
	0x14, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_comment_service_service_proto_rawDescOnce sync.Once
	file_pb_comment_service_service_proto_rawDescData = file_pb_comment_service_service_proto_rawDesc
)

func file_pb_comment_service_service_proto_rawDescGZIP() []byte {
	file_pb_comment_service_service_proto_rawDescOnce.Do(func() {
		file_pb_comment_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_comment_service_service_proto_rawDescData)
	})
	return file_pb_comment_service_service_proto_rawDescData
}

var file_pb_comment_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_comment_service_service_proto_goTypes = []any{
	(*FindAllByStoryIDRequest)(nil), // 0: pb.comment_service.FindAllByStoryIDRequest
	(*Comments)(nil),                // 1: pb.comment_service.Comments
}
var file_pb_comment_service_service_proto_depIdxs = []int32{
	0, // 0: pb.comment_service.CommentService.FindAllByStoryID:input_type -> pb.comment_service.FindAllByStoryIDRequest
	1, // 1: pb.comment_service.CommentService.FindAllByStoryID:output_type -> pb.comment_service.Comments
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_comment_service_service_proto_init() }
func file_pb_comment_service_service_proto_init() {
	if File_pb_comment_service_service_proto != nil {
		return
	}
	file_pb_comment_service_comment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_comment_service_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_comment_service_service_proto_goTypes,
		DependencyIndexes: file_pb_comment_service_service_proto_depIdxs,
		MessageInfos:      file_pb_comment_service_service_proto_msgTypes,
	}.Build()
	File_pb_comment_service_service_proto = out.File
	file_pb_comment_service_service_proto_rawDesc = nil
	file_pb_comment_service_service_proto_goTypes = nil
	file_pb_comment_service_service_proto_depIdxs = nil
}
