// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: pb/comment_service/service.proto

package comment_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentService_FindAllByStoryID_FullMethodName  = "/pb.comment_service.CommentService/FindAllByStoryID"
	CommentService_FindAllByStoryIDs_FullMethodName = "/pb.comment_service.CommentService/FindAllByStoryIDs"
)

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	FindAllByStoryID(ctx context.Context, in *FindAllByStoryIDRequest, opts ...grpc.CallOption) (*Comments, error)
	FindAllByStoryIDs(ctx context.Context, in *FindAllByStoryIDsRequest, opts ...grpc.CallOption) (*Comments, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) FindAllByStoryID(ctx context.Context, in *FindAllByStoryIDRequest, opts ...grpc.CallOption) (*Comments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comments)
	err := c.cc.Invoke(ctx, CommentService_FindAllByStoryID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) FindAllByStoryIDs(ctx context.Context, in *FindAllByStoryIDsRequest, opts ...grpc.CallOption) (*Comments, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comments)
	err := c.cc.Invoke(ctx, CommentService_FindAllByStoryIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations must embed UnimplementedCommentServiceServer
// for forward compatibility.
type CommentServiceServer interface {
	FindAllByStoryID(context.Context, *FindAllByStoryIDRequest) (*Comments, error)
	FindAllByStoryIDs(context.Context, *FindAllByStoryIDsRequest) (*Comments, error)
	mustEmbedUnimplementedCommentServiceServer()
}

// UnimplementedCommentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentServiceServer struct{}

func (UnimplementedCommentServiceServer) FindAllByStoryID(context.Context, *FindAllByStoryIDRequest) (*Comments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllByStoryID not implemented")
}
func (UnimplementedCommentServiceServer) FindAllByStoryIDs(context.Context, *FindAllByStoryIDsRequest) (*Comments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllByStoryIDs not implemented")
}
func (UnimplementedCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {}
func (UnimplementedCommentServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_FindAllByStoryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllByStoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindAllByStoryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_FindAllByStoryID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindAllByStoryID(ctx, req.(*FindAllByStoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_FindAllByStoryIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllByStoryIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).FindAllByStoryIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommentService_FindAllByStoryIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).FindAllByStoryIDs(ctx, req.(*FindAllByStoryIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.comment_service.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllByStoryID",
			Handler:    _CommentService_FindAllByStoryID_Handler,
		},
		{
			MethodName: "FindAllByStoryIDs",
			Handler:    _CommentService_FindAllByStoryIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/comment_service/service.proto",
}
